/**
 * ZICORE Simulation Engine — Client-side scene loader, physics, and agent behaviors.
 * Loads simulation scenes generated by simulation_engine.py and renders them in Three.js.
 * Provides real-time physics tick, entity behaviors, and HUD telemetry.
 * License: CC BY-NC-SA 4.0
 */
var SimEngine = (function () {
  'use strict';

  var simId = null;
  var scene, camera, renderer;
  var entities = [];
  var terrainMesh = null;
  var skyMesh = null;
  var clock = new THREE.Clock();
  var isRunning = false;
  var tickRate = 60;
  var tickInterval = null;
  var onHUDUpdate = null;

  function init(sid, threeScene, threeCamera, threeRenderer) {
    simId = sid;
    scene = threeScene;
    camera = threeCamera;
    renderer = threeRenderer;
    entities = [];
  }

  function loadScene(sid, callback) {
    simId = sid;
    fetch('/api/simulate/scene/' + sid)
      .then(function (r) { return r.json(); })
      .then(function (data) {
        if (data.error) { if (callback) callback(data.error); return; }
        buildScene(data, callback);
      })
      .catch(function (err) { if (callback) callback(err); });
  }

  function buildScene(data, callback) {
    clearScene();

    if (data.terrain && data.terrain.texture_url) {
      loadTerrain(data.terrain, data.environment);
    }

    (data.entities || []).forEach(function (ent, idx) {
      loadEntity(ent, idx, data);
    });

    if (data.environment) {
      setupEnvironment(data.environment);
    }

    isRunning = true;
    if (callback) callback(null, data);
  }

  function clearScene() {
    entities.forEach(function (e) {
      if (e.group && scene) scene.remove(e.group);
    });
    entities = [];
    if (terrainMesh && scene) scene.remove(terrainMesh);
    terrainMesh = null;
    if (skyMesh && scene) scene.remove(skyMesh);
    skyMesh = null;
  }

  function loadTerrain(terrain, env) {
    var texUrl = terrain.texture_url;
    var size = 50;
    var segs = 64;

    var geo = new THREE.PlaneGeometry(size, size, segs, segs);
    geo.rotateX(-Math.PI / 2);

    if (terrain.heightmap_url) {
      var loader = new THREE.TextureLoader();
      loader.load(terrain.heightmap_url, function (tex) {
        var canvas = document.createElement('canvas');
        canvas.width = tex.image.width;
        canvas.height = tex.image.height;
        var ctx = canvas.getContext('2d');
        ctx.drawImage(tex.image, 0, 0);
        var imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        var verts = geo.attributes.position.array;
        var scale = 3.0;
        for (var i = 0; i < verts.length; i += 3) {
          var u = (verts[i] / size + 0.5);
          var v = (verts[i + 2] / size + 0.5);
          var px = Math.floor(u * (canvas.width - 1));
          var py = Math.floor(v * (canvas.height - 1));
          var idx = (py * canvas.width + px) * 4;
          var h = imgData.data[idx] / 255.0;
          verts[i + 1] = h * scale;
        }
        geo.computeVertexNormals();
      });
    }

    var mat;
    if (terrain.texture_url) {
      var texLoader = new THREE.TextureLoader();
      var colorTex = texLoader.load(terrain.texture_url);
      mat = new THREE.MeshStandardMaterial({
        map: colorTex,
        roughness: 0.9,
        metalness: 0.0,
      });
    } else {
      var col = env && env.sky_color ? env.sky_color : [0.4, 0.25, 0.15];
      mat = new THREE.MeshStandardMaterial({
        color: new THREE.Color(col[0], col[1], col[2]),
        roughness: 0.9,
        metalness: 0.0,
      });
    }

    terrainMesh = new THREE.Mesh(geo, mat);
    terrainMesh.receiveShadow = true;
    if (scene) scene.add(terrainMesh);
  }

  function loadEntity(ent, idx, data) {
    var group = new THREE.Group();
    var pos = ent.position || [0, 0, 0];
    var rot = ent.rotation || [0, 0, 0];
    var sc = ent.scale || [1, 1, 1];
    group.position.set(pos[0], pos[1], pos[2]);
    group.rotation.set(rot[0] * Math.PI / 180, rot[1] * Math.PI / 180, rot[2] * Math.PI / 180);
    group.scale.set(sc[0], sc[1], sc[2]);

    var templateName = ent.template_name || 'habitat_dome';
    var mesh = createEntityMesh(templateName);
    if (mesh) group.add(mesh);

    if (scene) scene.add(group);

    var behavior = null;
    if (data.entity_assets && data.entity_assets[templateName]) {
      var spec = null;
      if (typeof data.entity_assets[templateName] === 'string') {
        try { spec = JSON.parse(data.entity_assets[templateName]); } catch (e) {}
      } else {
        spec = data.entity_assets[templateName];
      }
      if (spec && spec.tags) {
        if (spec.tags.indexOf('autonomous') >= 0) {
          behavior = { type: 'patrol', speed: 2.0, waypoints: [] };
        }
      }
    }

    entities.push({
      group: group,
      templateName: templateName,
      position: pos,
      rotation: rot,
      scale: sc,
      behavior: behavior,
      behaviorTime: Math.random() * 100,
      velocity: [0, 0, 0],
      mass: 1000,
    });
  }

  function createEntityMesh(templateName) {
    var shapes = {
      'habitat_dome': function () { return buildDome(); },
      'habitat_module': function () { return buildCylinder(2, 6, 24); },
      'underground_habitat': function () { return buildBox(10, 5, 15); },
      'cargo_rover': function () { return buildRover(); },
      'exploration_rover': function () { return buildRover(); },
      'drone_rover': function () { return buildDrone(); },
      'solar_array': function () { return buildSolarArray(); },
      'nuclear_reactor': function () { return buildCylinder(1.5, 3, 24); },
      'wind_turbine': function () { return buildTurbine(); },
      'fuel_depot': function () { return buildCylinder(2, 6, 24); },
      'landing_pad': function () { return buildBox(20, 0.5, 20); },
      'launch_clamp': function () { return buildBox(20, 20, 20); },
      'isru_unit': function () { return buildBox(3, 3, 4); },
      'science_lab': function () { return buildBox(4, 3, 5); },
      'communication_array': function () { return buildDish(); },
      'weather_station': function () { return buildMast(); },
      'greenhouse': function () { return buildBox(6, 4, 10); },
      'cargo_ship': function () { return buildCargoShip(); },
      'shuttle': function () { return buildSpaceplane(); },
      'cargo_container': function () { return buildBox(2, 2, 4); },
      'antenna_array': function () { return buildAntennaArray(); },
      'fuel_tank': function () { return buildCylinder(1.5, 5, 24); },
      'space_station': function () { return buildStation(); },
    };

    var builder = shapes[templateName];
    if (builder) return builder();

    return buildBox(1, 1, 1);
  }

  function buildDome() {
    var group = new THREE.Group();
    var base = new THREE.Mesh(
      new THREE.CylinderGeometry(5, 5, 2, 32),
      new THREE.MeshPhongMaterial({ color: 0x8899aa, roughness: 0.6, metalness: 0.4 })
    );
    base.position.y = 1;
    group.add(base);

    var dome = new THREE.Mesh(
      new THREE.SphereGeometry(5, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2),
      new THREE.MeshPhongMaterial({
        color: 0x00e5ff, transparent: true, opacity: 0.3,
        roughness: 0.1, metalness: 0.0, side: THREE.DoubleSide
      })
    );
    dome.position.y = 2;
    group.add(dome);

    var ring = new THREE.Mesh(
      new THREE.TorusGeometry(5.5, 0.1, 8, 48),
      new THREE.MeshBasicMaterial({ color: 0x00e5ff })
    );
    ring.position.y = 2;
    ring.rotation.x = Math.PI / 2;
    group.add(ring);

    return group;
  }

  function buildBox(w, h, d) {
    return new THREE.Mesh(
      new THREE.BoxGeometry(w, h, d),
      new THREE.MeshPhongMaterial({ color: 0x8899aa, roughness: 0.7, metalness: 0.3 })
    );
  }

  function buildCylinder(r, h, segs) {
    return new THREE.Mesh(
      new THREE.CylinderGeometry(r, r, h, segs || 24),
      new THREE.MeshPhongMaterial({ color: 0x8899aa, roughness: 0.6, metalness: 0.5 })
    );
  }

  function buildSolarArray() {
    var group = new THREE.Group();
    var panel = new THREE.Mesh(
      new THREE.BoxGeometry(0.1, 4, 8),
      new THREE.MeshPhongMaterial({ color: 0x2244aa, roughness: 0.3, metalness: 0.8 })
    );
    group.add(panel);
    var pole = new THREE.Mesh(
      new THREE.CylinderGeometry(0.05, 0.05, 1, 8),
      new THREE.MeshPhongMaterial({ color: 0x666666, roughness: 0.5, metalness: 0.7 })
    );
    pole.position.y = -2.5;
    group.add(pole);
    return group;
  }

  function buildRover() {
    var group = new THREE.Group();
    var body = new THREE.Mesh(
      new THREE.BoxGeometry(2.5, 1.0, 4.0),
      new THREE.MeshPhongMaterial({ color: 0x667788, roughness: 0.8, metalness: 0.4 })
    );
    body.position.y = 1.5;
    group.add(body);
    for (var sx = -1.2; sx <= 1.2; sx += 2.4) {
      for (var sz = -1.5; sz <= 1.5; sz += 3) {
        var wheel = new THREE.Mesh(
          new THREE.CylinderGeometry(0.4, 0.4, 0.3, 12),
          new THREE.MeshPhongMaterial({ color: 0x333333, roughness: 0.9, metalness: 0.1 })
        );
        wheel.position.set(sx, 0.4, sz);
        wheel.rotation.x = Math.PI / 2;
        group.add(wheel);
      }
    }
    return group;
  }

  function buildDrone() {
    var group = new THREE.Group();
    var body = new THREE.Mesh(
      new THREE.BoxGeometry(1.5, 0.3, 1.5),
      new THREE.MeshPhongMaterial({ color: 0x8899aa, roughness: 0.5, metalness: 0.6 })
    );
    body.position.y = 0.15;
    group.add(body);
    for (var sx = -0.7; sx <= 0.7; sx += 1.4) {
      for (var sz = -0.7; sz <= 0.7; sz += 1.4) {
        var motor = new THREE.Mesh(
          new THREE.CylinderGeometry(0.1, 0.1, 0.05, 8),
          new THREE.MeshPhongMaterial({ color: 0x444444, roughness: 0.5, metalness: 0.5 })
        );
        motor.position.set(sx, 0.3, sz);
        group.add(motor);
      }
    }
    return group;
  }

  function buildDish() {
    var group = new THREE.Group();
    var dish = new THREE.Mesh(
      new THREE.ConeGeometry(1.5, 0.3, 24),
      new THREE.MeshPhongMaterial({ color: 0xaabbcc, roughness: 0.2, metalness: 0.8 })
    );
    dish.position.y = 0.8;
    group.add(dish);
    var pole = new THREE.Mesh(
      new THREE.CylinderGeometry(0.05, 0.05, 0.8, 8),
      new THREE.MeshPhongMaterial({ color: 0x666666, roughness: 0.5, metalness: 0.7 })
    );
    pole.position.y = 0.4;
    group.add(pole);
    return group;
  }

  function buildMast() {
    var group = new THREE.Group();
    var pole = new THREE.Mesh(
      new THREE.CylinderGeometry(0.08, 0.1, 4, 8),
      new THREE.MeshPhongMaterial({ color: 0x666666, roughness: 0.5, metalness: 0.7 })
    );
    pole.position.y = 2;
    group.add(pole);
    var sensor = new THREE.Mesh(
      new THREE.SphereGeometry(0.2, 8, 8),
      new THREE.MeshPhongMaterial({ color: 0x00ff88, emissive: 0x00ff88, emissiveIntensity: 0.3 })
    );
    sensor.position.y = 4;
    group.add(sensor);
    return group;
  }

  function buildTurbine() {
    var group = new THREE.Group();
    var tower = new THREE.Mesh(
      new THREE.CylinderGeometry(0.3, 0.5, 8, 8),
      new THREE.MeshPhongMaterial({ color: 0x666666, roughness: 0.5, metalness: 0.7 })
    );
    tower.position.y = 4;
    group.add(tower);
    var nacelle = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.5, 0.8),
      new THREE.MeshPhongMaterial({ color: 0x8899aa, roughness: 0.5, metalness: 0.5 })
    );
    nacelle.position.y = 8;
    group.add(nacelle);
    return group;
  }

  function buildCargoShip() {
    var group = new THREE.Group();
    var body = new THREE.Mesh(
      new THREE.BoxGeometry(3, 3, 12),
      new THREE.MeshPhongMaterial({ color: 0x8899aa, roughness: 0.4, metalness: 0.7 })
    );
    body.position.y = 6;
    group.add(body);
    var engine = new THREE.Mesh(
      new THREE.ConeGeometry(1.5, 2, 16),
      new THREE.MeshPhongMaterial({ color: 0x444444, roughness: 0.6, metalness: 0.8 })
    );
    engine.position.set(0, 1.5, -6);
    engine.rotation.x = Math.PI / 2;
    group.add(engine);
    return group;
  }

  function buildSpaceplane() {
    var group = new THREE.Group();
    var body = new THREE.Mesh(
      new THREE.BoxGeometry(4, 2, 15),
      new THREE.MeshPhongMaterial({ color: 0x8899aa, roughness: 0.4, metalness: 0.6 })
    );
    body.position.y = 1;
    group.add(body);
    [-4, 4].forEach(function (x) {
      var wing = new THREE.Mesh(
        new THREE.BoxGeometry(0.5, 0.2, 8),
        new THREE.MeshPhongMaterial({ color: 0x778899, roughness: 0.5, metalness: 0.5 })
      );
      wing.position.set(x, 0.5, 0);
      group.add(wing);
    });
    return group;
  }

  function buildStation() {
    var group = new THREE.Group();
    var core = new THREE.Mesh(
      new THREE.BoxGeometry(8, 2, 8),
      new THREE.MeshPhongMaterial({ color: 0x8899aa, roughness: 0.4, metalness: 0.7 })
    );
    core.position.y = 1;
    group.add(core);
    for (var i = 0; i < 4; i++) {
      var angle = i * Math.PI / 2;
      var x = Math.cos(angle) * 6;
      var z = Math.sin(angle) * 6;
      var mod = new THREE.Mesh(
        new THREE.CylinderGeometry(2, 2, 6, 16),
        new THREE.MeshPhongMaterial({ color: 0x99aabb, roughness: 0.4, metalness: 0.6 })
      );
      mod.position.set(x, 0, z);
      group.add(mod);
    }
    return group;
  }

  function buildAntennaArray() {
    var group = new THREE.Group();
    for (var i = 0; i < 4; i++) {
      var angle = i * Math.PI / 2;
      var x = Math.cos(angle) * 2;
      var z = Math.sin(angle) * 2;
      var pole = new THREE.Mesh(
        new THREE.CylinderGeometry(0.05, 0.05, 3, 8),
        new THREE.MeshPhongMaterial({ color: 0x666666, roughness: 0.5, metalness: 0.7 })
      );
      pole.position.set(x, 1.5, z);
      group.add(pole);
      var dish = new THREE.Mesh(
        new THREE.ConeGeometry(0.5, 0.2, 12),
        new THREE.MeshPhongMaterial({ color: 0xaabbcc, roughness: 0.2, metalness: 0.8 })
      );
      dish.position.set(x, 3, z);
      group.add(dish);
    }
    var base = new THREE.Mesh(
      new THREE.BoxGeometry(6, 0.2, 6),
      new THREE.MeshPhongMaterial({ color: 0x667788, roughness: 0.6, metalness: 0.4 })
    );
    group.add(base);
    return group;
  }

  function setupEnvironment(env) {
    if (!scene) return;
    if (env.sky_color) {
      var skyCol = new THREE.Color(env.sky_color[0], env.sky_color[1], env.sky_color[2]);
      scene.background = skyCol;
      scene.fog = new THREE.Fog(skyCol, 60, 100);
    }
  }

  function getStats() {
    if (entities.length === 0) return null;
    var totalMass = 0;
    entities.forEach(function (e) { totalMass += e.mass || 1000; });
    return {
      entityCount: entities.length,
      totalMass: totalMass,
      bodyCount: entities.length,
      isRunning: isRunning,
    };
  }

  function startPhysics() {
    if (tickInterval) return;
    isRunning = true;
    tick();
  }

  function stopPhysics() {
    isRunning = false;
    if (tickInterval) { clearInterval(tickInterval); tickInterval = null; }
  }

  var tickAccum = 0;
  function tick() {
    var dt = clock.getDelta();
    if (dt > 0.05) dt = 0.05;
    tickAccum += dt;

    if (tickAccum >= 1 / tickRate) {
      tickAccum = 0;
      updateBehaviors(dt);
      updatePhysics(dt);
    }

    if (isRunning && renderer && scene && camera) {
      renderer.render(scene, camera);
    }

    requestAnimationFrame(tick);
  }

  function updateBehaviors(dt) {
    entities.forEach(function (ent) {
      if (!ent.behavior) return;
      ent.behaviorTime += dt;

      switch (ent.behavior.type) {
        case 'patrol':
          var speed = ent.behavior.speed || 2.0;
          ent.group.position.x += Math.sin(ent.behaviorTime * 0.5) * speed * dt * 0.1;
          ent.group.position.z += Math.cos(ent.behaviorTime * 0.3) * speed * dt * 0.1;
          ent.group.rotation.y = Math.atan2(
            Math.cos(ent.behaviorTime * 0.3) * speed * dt * 0.1,
            Math.sin(ent.behaviorTime * 0.5) * speed * dt * 0.1
          );
          break;

        case 'orbit':
          var radius = ent.behavior.radius || 50;
          var speed = ent.behavior.speed || 5.0;
          var target = ent.behavior.target || '';
          ent.group.position.x = radius * Math.cos(ent.behaviorTime * 0.01 * speed);
          ent.group.position.z = radius * Math.sin(ent.behaviorTime * 0.01 * speed);
          break;

        case 'track_sun':
          ent.group.rotation.y = ent.behaviorTime * 0.1;
          break;

        case 'rotate':
          var axis = ent.behavior.axis || 'y';
          var speed = ent.behavior.speed || 30.0;
          if (axis === 'y') ent.group.rotation.y += speed * dt * Math.PI / 180;
          else if (axis === 'x') ent.group.rotation.x += speed * dt * Math.PI / 180;
          else if (axis === 'z') ent.group.rotation.z += speed * dt * Math.PI / 180;
          break;

        case 'idle':
          break;
      }
    });
  }

  function updatePhysics(dt) {
    entities.forEach(function (ent) {
      if (ent.behavior && ent.behavior.type === 'hover') {
        ent.group.position.y += Math.sin(ent.behaviorTime * 2) * 0.01;
      }
    });
  }

  function getEntityPositions() {
    return entities.map(function (e) {
      return {
        id: e.templateName,
        pos: [e.group.position.x, e.group.position.y, e.group.position.z],
        rot: [e.group.rotation.x, e.group.rotation.y, e.group.rotation.z],
      };
    });
  }

  return {
    init: init,
    loadScene: loadScene,
    buildScene: buildScene,
    clearScene: clearScene,
    getStats: getStats,
    startPhysics: startPhysics,
    stopPhysics: stopPhysics,
    getEntityPositions: getEntityPositions,
    loadEntity: loadEntity,
  };
})();
